server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: REG-SERVICE
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://reg-service
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST

        - id: PRODUCT-SERVICE
          uri: lb://product-service
          predicates:
            - Method=GET,POST

        - id: EMAIL-SERVICE
          uri: lb://email-service
          predicates:
            - Method=GET,POST
## 使用 Sentinel 作为熔断器
#    sentinel:
#      transport:
#        dashboard:
#        port:

management:
  endpoints:
    web:
      exposure:
        include: "*"