spring:
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: localhost:9876
        bindings:
          input: {consumer.orderly: true}
      bindings:
        EMAIL_OUTPUT: {destination: topic-email, content-type: application/json}
        EMAIL_INPUT: {destination: topic-email, content-type: application/json, group: group-email, consumer.maxAttempts: 1}