spring:
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: localhost:9876
        bindings:
          input: {consumer.orderly: true}
      bindings:
        REG_OUTPUT: {destination: reg-topic, content-type: application/json}
        REG_INPUT: {destination: reg-topic, content-type: application/json, group: reg-group, consumer.maxAttempts: 1}